### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jibanes** [GregGuazzone/OptionStrategy#1]
``$ python3 expected_profit.py 2023-08-11 AAPL 
Traceback (most recent call last):
  File "xxx/OptionStrategy-main/venv/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 414, in get_loc
    return self._range.index(new_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "xxx/OptionStrategy-main/expected_profit.py", line 146, in <module>
    main()
  File "xxx/OptionStrategy-main/expected_profit.py", line 122, in main
    profit_calculator = Strategy(date=date, ticker=ticker, depth=1)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx/OptionStrategy-main/expected_profit.py", line 18, in __init__
    self.stock_price = yo.get_underlying_price(self.calls['Symbol'][0])
                                               ~~~~~~~~~~~~~~~~~~~~^^^
  File "xxx/OptionStrategy-main/venv/lib/python3.11/site-packages/pandas/core/series.py", line 1040, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "xxx/OptionStrategy-main/venv/lib/python3.11/site-packages/pandas/core/series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xxx/OptionStrategy-main/venv/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 416, in get_loc
    raise KeyError(key) from err
KeyError: 0``

**Comment by GregGuazzone** [comment]
Past expirations dates are not supported, to get the available expiration dates use:

 `python3 expected_profit.py <ticker> --exp_dates`  then choosing from available futures dates:
 `python3 expected_profit.py AAPL 2024-06-21`
 
I also switched the order between ticker and date options.
It's also worth nothing that if the chosen expiration is the current date, it might run into some issues.
